const views={
  teams:{title:"Team season profiles",metricLabel:"Stat group",metrics:{summary:["Team","GP","Record","Win %","Home record","Road record","PPG","Opp PPG","Point diff"],efficiency:["Team","GP","Pace","OffRtg","DefRtg","NetRtg","FG%","eFG%","TS%","3P rate","FT rate"],scoring:["Team","GP","PPG","Opp PPG","Paint PPG","Fast break","Off TO pts","FGM","FGA","FG%","3PM","3PA","3P%","FTM","FTA","FT%"],other:["Team","GP","ORB","DRB","REB","AST","STL","BLK","TOV","PF"]},
    keys:{summary:["team","gp","record","pct","home","road","ppg","opp_ppg","point_diff"],efficiency:["team","gp","pace","ortg","drtg","netrtg","fg_pct","efg_pct","ts_pct","three_rate","ft_rate"],scoring:["team","gp","ppg","opp_ppg","paint","fastbreak","tov_pts","fgm","fga","fg_pct","tpm","tpa","tp_pct","ftm","fta","ft_pct"],other:["team","gp","orb","drb","reb","ast","stl","blk","tov","pf"]}},
  players:{title:"Player season production",metricLabel:"Stat group",metrics:{production:["Team","Player","GP","GS","MIN","PTS","REB","AST","STL","BLK","TOV","+/-/G"],shooting:["Team","Player","GP","PTS","FGM","FGA","FG%","3PM","3PA","3P%","FTM","FTA","FT%","eFG%","TS%"],rates:["Team","Player","GP","MIN","PTS/36","REB/36","AST/36","STL/36","BLK/36","TOV/36","Usage %"]},
    keys:{production:["team","player","gp","gs","min","pts","reb","ast","stl","blk","tov","plus_minus_pg"],shooting:["team","player","gp","pts","fgm","fga","fg_pct","tpm","tpa","tp_pct","ftm","fta","ft_pct","efg_pct","ts_pct"],rates:["team","player","gp","min","pts36","reb36","ast36","stl36","blk36","tov36","usg_pct"]}},
  games:{title:"Team game log",metricLabel:"Stat group",metrics:{score:["Date","Team","Opp","H/A","Result","Score","Margin","Poss","OffRtg","DefRtg"],shooting:["Date","Team","Opp","Result","Score","FGM","FGA","FG%","3PM","3PA","3P%","FTM","FTA","FT%"],box:["Date","Team","Opp","Result","Score","REB","AST","STL","BLK","TOV","PF","Paint","Fast break","TO points"]},
    keys:{score:["date","team","opponent","venue","result","score","margin","poss","ortg","drtg"],shooting:["date","team","opponent","result","score","fgm","fga","fg_pct","tpm","tpa","tp_pct","ftm","fta","ft_pct"],box:["date","team","opponent","result","score","reb","ast","stl","blk","tov","pf","paint","fastbreak","tov_pts"]}}
};
const formatPct=new Set(["pct","fg_pct","tp_pct","ft_pct","efg_pct","ts_pct","three_rate","ft_rate","usg_pct"]),integer=new Set(["gp","gs","score","opp_score","fgm","fga","tpm","tpa","ftm","fta","orb","drb","reb","ast","stl","blk","tov","pf","paint","fastbreak","tov_pts"]);
boot(async()=>{
  const [index,teamData]=await Promise.all([getJSON("stats_index.json"),getJSON("team_stats.json")]);
  const datasets={teams:teamData.rows,players:[],games:[]}, cache={}, buttons=[...document.querySelectorAll("[data-view]")];
  const season=$("statsSeason"),type=$("statsType"),team=$("statsTeam"),search=$("statsSearch"),metric=$("statsMetric"),head=$("statsHead"),body=$("statsBody");
  const years=index.seasons.teams;
  season.innerHTML=years.map(y=>'<option value="'+y+'">'+(y-1)+'–'+String(y).slice(-2)+'</option>').join("");
  const teams=[...new Set(datasets.teams.map(r=>r.team).filter(t=>t!=="TOT"))].sort();
  team.innerHTML='<option value="">All teams</option>'+teams.map(t=>'<option value="'+esc(t)+'">'+esc(t)+" · "+esc(NAMES[t]||t)+"</option>").join("");
  let view="teams", sortKey="", sortDirection=-1;
  function display(v,k){if(v==null)return "–";if(typeof v==="string")return esc(v);if(!Number.isFinite(Number(v)))return "–";if(formatPct.has(k))return (Number(v)*100).toFixed(1)+"%";if(k==="min")return Number(v).toFixed(0);if(integer.has(k))return Number(v).toFixed(0);if(typeof v==="number")return v.toFixed(1);return esc(v);}
  function label(k){return ({team:"Team",player:"Player",teams:"Teams",gp:"GP",gs:"GS",min:"MIN",pts:"PTS",reb:"REB",ast:"AST",stl:"STL",blk:"BLK",tov:"TOV",pf:"PF",fgm:"FGM",fga:"FGA",tpm:"3PM",tpa:"3PA",ftm:"FTM",fta:"FTA",pct:"Win %",home:"Home record",road:"Road record",ppg:"PPG",opp_ppg:"Opp PPG",point_diff:"Point diff",pace:"Pace",ortg:"OffRtg",drtg:"DefRtg",netrtg:"NetRtg",fg_pct:"FG%",tp_pct:"3P%",ft_pct:"FT%",efg_pct:"eFG%",ts_pct:"TS%",three_rate:"3P rate",ft_rate:"FT rate",paint:"Paint PPG",fastbreak:"Fast break",tov_pts:"TO points",orb:"ORB",drb:"DRB",pts36:"PTS/36",reb36:"REB/36",ast36:"AST/36",stl36:"STL/36",blk36:"BLK/36",tov36:"TOV/36",usg_pct:"Usage %",plus_minus_pg:"+/-/G",date:"Date",opponent:"Opp",venue:"H/A",result:"Result",score:"Score",margin:"Margin",poss:"Poss"})[k]||k;}
  function build(){
    const cfg=views[view], group=cfg.metrics[metric.value]||Object.keys(cfg.metrics)[0], keys=cfg.keys[group];
    $("statsTitle").textContent=cfg.title; $("metricField").style.display=view==="games"?"none":"";
    $("statsNote").textContent=view==="teams"?"Season averages use games played. Efficiency rates are calculated from box-score possessions; they are descriptive and not adjusted for opponent strength.":view==="players"?"Player box-score totals and rate stats are shown by season. TOT combines a player's team stints; team splits remain available. Usage is an estimate from box-score possessions.":"Each row is one team in one game. The opponent appears as a separate row so you can compare a team's game log directly with its season profile.";
    const selectedSeason=Number(season.value), selectedType=Number(type.value), selectedTeam=team.value, q=search.value.trim().toLowerCase();
    let rows=(datasets[view]||[]).filter(r=>r.season===selectedSeason&&r.season_type===selectedType&&(!selectedTeam||r.team===selectedTeam));
    if(q)rows=rows.filter(r=>String(r.player||r.name||r.team||"").toLowerCase().includes(q)||(view==="games"&&String(r.opponent).toLowerCase().includes(q))||(view==="players"&&String(r.teams).toLowerCase().includes(q)));
    if(sortKey)rows.sort((a,b)=>{const x=a[sortKey],y=b[sortKey];let n;if(x==null)n=y==null?0:1;else if(y==null)n=-1;else n=typeof x==="string"?String(x).localeCompare(String(y)):Number(x)-Number(y);return n*sortDirection;});
    else if(view==="players")rows.sort((a,b)=>(b.pts||0)-(a.pts||0)); else rows.sort((a,b)=>String(a.date||"").localeCompare(String(b.date||""))*-1);
    $("rowCount").textContent=rows.length.toLocaleString()+" rows";
    head.innerHTML="<tr>"+keys.map(k=>'<th data-key="'+k+'" data-type="'+(["date","team","player","opponent","result","venue"].includes(k)?"text":"num")+'">'+esc(label(k))+"</th>").join("")+"</tr>";
    head.querySelectorAll("th").forEach(th=>th.addEventListener("click",()=>{const key=th.dataset.key;if(sortKey===key)sortDirection*=-1;else{sortKey=key;sortDirection=th.dataset.type==="text"?1:-1;}build();}));
    body.innerHTML=rows.map(r=>"<tr>"+keys.map(k=>{let v=r[k];if(k==="team"&&view==="players"&&r.team==="TOT")v=r.teams+" (TOT)";if(k==="record")v=(r.w||0)+"–"+(r.l||0);if(k==="home")v=(r.home_w||0)+"–"+((r.home_gp||0)-(r.home_w||0));if(k==="road")v=(r.road_w||0)+"–"+((r.road_gp||0)-(r.road_w||0));if(k==="date")v=String(v||"");return '<td class="'+(["team","player","date","opponent","result"].includes(k)?"txt":"")+'">'+display(v,k)+"</td>";}).join("")+"</tr>").join("")||'<tr><td colspan="'+keys.length+'" class="txt">No rows match these filters.</td></tr>';
  }
  async function loadCurrent(){const current=view,year=Number(season.value);if(current==="teams"){build();return;}const key=current+":"+year;if(!cache[key]){const file=current==="players"?"player_stats_":"team_games_";cache[key]=getJSON(file+year+".json").then(x=>x.rows).catch(()=>[]);}$("rowCount").textContent="Loading season data…";const rows=await cache[key];if(view===current&&Number(season.value)===year){datasets[current]=rows;build();}}
  async function setView(next){view=next;sortKey="";buttons.forEach(b=>{const active=b.dataset.view===view;b.classList.toggle("active",active);b.setAttribute("aria-selected",String(active));});const viewYears=index.seasons[view];const oldSeason=season.value;season.innerHTML=viewYears.map(y=>'<option value="'+y+'">'+(y-1)+'–'+String(y).slice(-2)+'</option>').join("");season.value=viewYears.includes(Number(oldSeason))?oldSeason:String(viewYears[0]);const groups=Object.keys(views[view].metrics);metric.innerHTML=groups.map(g=>'<option value="'+g+'">'+({summary:"Summary",efficiency:"Efficiency",scoring:"Scoring & shooting",other:"Rebounding & creation",production:"Production",shooting:"Shooting",rates:"Per 36 & usage",score:"Score & efficiency",box:"Box score"}[g]||g)+"</option>").join("");await loadCurrent();}
  buttons.forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));season.addEventListener("change",()=>view==="teams"?build():loadCurrent());[type,team,metric].forEach(el=>el.addEventListener("change",build));search.addEventListener("input",build);
  season.value=String(years[0]);setView("teams");
});
